In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [9]:
A = np.array([[1, 2], [2, 1]])
A

array([[1, 2],
       [2, 1]])

In [10]:
np.linalg.eig(A)

EigResult(eigenvalues=array([ 3., -1.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))

In [11]:
eigenvalues, eigenvec = np.linalg.eig(A)

In [12]:
P = eigenvec
P

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [13]:
P_inv = np.linalg.inv(P)
P_inv

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [14]:
D = np.diag(eigenvalues)
D

array([[ 3.,  0.],
       [ 0., -1.]])

In [16]:
P @ D @ P_inv

array([[1., 2.],
       [2., 1.]])