In [1]:
import numpy as np
scalar = np.array([10])
scalar

array([10])

In [2]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array = np.array([1, 2.5, 3, 4.8, 8])
array.dtype

dtype('float64')

In [5]:
array = np.array([1, 2.5, "hello", 4.8, 8])
array

array(['1', '2.5', 'hello', '4.8', '8'], dtype='<U32')

In [6]:
array = np.array ([1, 2, 3, 4, 5])
#array.append(6)
#array.pop(0)
array2 = np.array([5, 6 , 7, 8])
array3 = np.concat([array, array2])
array3

array([1, 2, 3, 4, 5, 5, 6, 7, 8])

In [ ]:
np.random.rand (1, 3) #numeros aleaorios

array([[0.0871293 , 0.0202184 , 0.83261985]])

In [32]:
random_array = np.random.rand(3, 3)
random_array

array([[0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805]])

In [33]:
my_array = random_array.reshape(3, 3)
my_array

array([[0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805]])

In [34]:
my_array.T

array([[0.2961402 , 0.41426299, 0.56660145],
       [0.11872772, 0.0641475 , 0.26538949],
       [0.31798318, 0.69247212, 0.52324805]])

In [24]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((3, 3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [35]:
unos = np.ones((3, 3))
unos * 2 + my_array

array([[2.2961402 , 2.11872772, 2.31798318],
       [2.41426299, 2.0641475 , 2.69247212],
       [2.56660145, 2.26538949, 2.52324805]])

In [41]:
new_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [42]:
new_matrix.std(), new_matrix.var()
std = new_matrix.std()
std

np.float64(2.581988897471611)

In [44]:
var = new_matrix.var()
var

np.float64(6.666666666666667)

In [46]:
new_matrix = np.linspace(1, 9, 9).reshape(3, 3)
new_matrix

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [47]:
new_matrix = np.arange(1, 10)
new_matrix

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
A = np.array([
    [1, 2],
    [3, 4]
])

np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])